baseURL: https://roaddust2.tatar/
title: roaddust2.tatar
theme: PaperModX


# Main params
params:
  # Main settings
  env: production
  useCustomAnalytics: true # Use Umami analytics (self-hosted)
  
  # Theme settings
  displayFullLangName: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true

  # Analytics
  goatcounter: roaddust2.tatar


# Search settings

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search


# Misc

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

markup:
    highlight:
        noClasses: false

permalinks:
  posts: /:section/:year/:month/:slugorfilename


# Language settings

defaultContentLanguage: ru
defaultContentLanguageInSubdir: true
languages:
  ru:
    contentDir: content/ru
    languageName: ":ru: Ru"
    weight: 1
    params:
      description: "Заметки работника стартапа"

      homeInfoParams:
        Title: ":wave: Добро пожаловать в мой блог!"
        Content: Он содержит инструкции, конфигурации, настройки сервера, 
          другие dev ресурсы, а также просто мои мысли и заметки. 
          Вместо того, чтобы полагаться на память, я решил документировать что-то для удобства.
          Не стесняйся исследовать; возможно, ты обнаружишь что-то полезное. Или нет.
      socialIcons:
        - name: github-simple
          title: Github
          url: "https://github.com/roaddust2"
        - name: rss-simple
          title: RSS
          url: "https://roaddust2.tatar/ru/index.xml"

  en:
    contentDir: content/en
    languageName: ":uk: En"
    weight: 2
    params:
      description: "Notes of startup employee"

      homeInfoParams:
        Title: ":wave: Welcome to my blog!"
        Content: It contains instructions, configurations, server setups, other development 
          resources and some of my thoughts. Instead of relying on memory, 
          I’ve documented everything there for easy reference. 
          Feel free to explore; you might discover something helpful. Or not.
      socialIcons:
        - name: github-simple
          title: Github
          url: "https://github.com/roaddust2"
        - name: rss-simple
          title: RSS
          url: "https://roaddust2.tatar/en/index.xml"
