# Menu settings for 'en' locale

main:
- name: Posts
  url: /en/posts/
  weight: 1
- name: Categories
  url: /en/categories/
  weight: 2
- name: Search
  url: /en/search/
  weight: 3
- name: Archive
  url: /en/archive/
  weight: 4